# This is a template toml file. Make sure to update kv_namespace id
# and the route.
name = "kimlikdao-ipfs"
main = "../build/lightNode.js"
workers_dev = false
no_bundle = true
minify = false
send_metrics = false
node_compat = false

[route]
pattern = "ipfs.kimlikdao.org"
custom_domain = true

[[kv_namespaces]]
binding = "KeyValue"
id = "52b51a1db0ce4508a144633d407dab93"
