name = "kimlikdao-node"
main = "../build/monolithicSignerNode.js"
compatibility_date = "2023-01-01"
workers_dev = false
usage_model = "unbound"
no_bundle = true
minify = false
send_metrics = false
node_compat = false
logpush = false

[route]
pattern = "node.kimlikdao.org"
custom_domain = true

[vars]
KIMLIKDAO_POW_THRESHOLD = "20000"

[[kv_namespaces]]
binding = "KeyValue"
id = "52b51a1db0ce4508a144633d407dab93"
preview_id = "1698646e36364585a5721f5b8c9697dd"
