name = "kimlikdao-node-nko-worker"
main = "../build/nkoWorker.js"
compatibility_date = "2023-01-01"
workers_dev = false
usage_model = "unbound"
no_bundle = true
minify = false
send_metrics = false
node_compat = false

[vars]
KIMLIKDAO_POW_THRESHOLD = "20000"

[[services]]
binding = "ExposureReportWorker"
service = "kimlikdao-node-exposurereport-worker"

[[services]]
binding = "HumanIDWorker"
service = "kimlikdao-node-humanid-worker"
