name = "kimlikdao-ipfs"
main = "../build/cloudflare/lightnode.js"

route = { pattern = "ipfs.kimlikdao.org", custom_domain = true }

kv_namespaces = [
    { binding = "KV", id = "52b51a1db0ce4508a144633d407dab93" }
]
compatibility_date = "2023-01-01"
workers_dev = false
usage_model = "bundled"
no_bundle = true
minify = false
send_metrics = false
node_compat = false
