name = "kimlikdao-node-humanid-worker"
main = "../build/humanIDWorker.js"
compatibility_date = "2023-01-01"
workers_dev = false
usage_model = "unbound"
no_bundle = true
minify = false
send_metrics = false
node_compat = false
