name: All tests

on:
  push:
    branches: ["main", "prod"]
  pull_request:
    branches: ["main", "prod"]

jobs:
  checkSignerNode:
    if: false
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i

      - name: Build exposureReportWorker
        run: make build/exposureReportWorker.js

      - name: Build humanIDWorker
        run: make build/humanIDWorker.js

      - name: Build oauth2Worker
        run: make build/oauth2Worker.js

      - name: Build nkoWorker
        run: make build/nkoWorker.js

      - name: Build signerNode
        run: make build/signerNode.js

  checkLightNode:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i

      - name: Build lightNode
        run: make build/lightNode.js

  checkCrateServer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Run tests
        run: cargo test --all --verbose
