name: All tests

on:
  push:
    branches: ["main", "prod"]
  pull_request:
    branches: ["main", "prod"]

jobs:
  check:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build signerNode
        run: |
          yarn
          make build/signerNode.js

      - name: Build lightNode
        run: |
          yarn
          make build/lightNode.js
