name: All tests

on:
  push:
    branches: ["main", "prod"]
  pull_request:
    branches: ["main", "prod"]

jobs:
  checkSignerNode:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i

      - name: Build nkoWorker
        run: make build/nkoWorker.js

      - name: Build signerNode
        run: make build/signerNode.js

  checkLightNode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i

      - name: Build lightNode
        run: make build/lightNode.js
